#!/bin/bash

#To use this script, open the Terminal app and go to the directry
#where this script is located and excecute the following commands:
	# chmod u+x PleaseSleep

	# ./PleaseSleep install
	# -------- OR ---------
	# ./PleaseSleep remove

# Get the argument
set -e
ARG=$1

# quit if any command fails
if [ -z "$1" ] ; then
	echo "Error: No parameter. Use 'PleaseSleep install' or 'PleaseSleep remove'."
	exit 1


# REMOVE EVERYTHING
elif [ "$ARG" == "remove" ] || [ "$ARG" == "uninstall" ]
then
	echo
	echo
	echo "REMOVING PleaseSleep with sleepwatcher 2.2.1"
	echo "This will remove all PleaseSleep AND all Sleepwatcher files."
	echo "This also includes the sleep and wake scripts."
	echo
	echo "Are you sure you want to continue?"
	echo "Press Enter to continue or Crtl+c to quit"
	read
	echo "-------------------------------------------------------------------"
	echo

	echo "Unloading the LaunchAgent..."
	launchctl unload ~/Library/LaunchAgents/de.bernhard-baehr.sleepwatcher.plist &> /dev/null
	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo

	echo "Removing sleep and wake scripts ..."
	rm ~/.sleep &> /dev/null
	rm ~/.wakeup &> /dev/null
	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo

	echo "Removing Sleepwatcher 2.2.1 and all the files ..."
	brew uninstall sleepwatcher

	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo

	echo "-------------------------------------------------------------------"
	echo

	echo "PleaseSleep and Sleepwatcher 2.2.1 are successfully removed from your lovely Mac!!"
	echo
	echo
	echo


# INSTALL EVERYTHING
elif [ "$1" == "install" ]
then
	echo
	echo
	echo "INSTALLING PleaseSleep with sleepwatcher 2.2.1"
	echo
	echo "Are you sure you want to continue?"
	echo "Press Enter to continue or Crtl+c to quit"
	read
	echo "-------------------------------------------------------------------"
	echo

	echo "Gaining permissions for /usr/local ..."
	# source: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md
	sudo chown -R $(whoami):admin /usr/local/*
	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo

	echo "Installing Sleepwatcher 2.2.1 (using the brew command)."
	echo "Please follow the instructions when prompted ..."
	echo "(Press ENTER key to continue.)"
	read
	echo
	brew install sleepwatcher
	echo
	echo
	echo "(Press ENTER key to continue.)"
	read
	echo

	echo "Creating the sleep script ..."
		rm -rf ~/.sleep
		touch ~/.sleep
		chmod u+x ~/.sleep
		echo "#! /bin/bash" > ~/.sleep
		echo "echo" >> ~/.sleep
		echo "echo $(date "+%Y-%m-%d %H:%M:%S") \"Sleeping\" >> /tmp/sleep.log" >> ~/.sleep
		echo "/usr/sbin/networksetup setairportpower en0 off" >> ~/.sleep
		echo "echo $(date "+%Y-%m-%d %H:%M:%S") `/usr/sbin/networksetup getairportpower en0` >> /tmp/sleep.log" >> ~/.sleep
	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo

	echo "Creating the wake script ..."
		rm -rf ~/.wakeup
		touch ~/.wakeup
		chmod u+x ~/.wakeup
		echo "#! /bin/bash" > ~/.wakeup
		echo "echo" >> ~/.wakeup
		echo "echo $(date "+%Y-%m-%d %H:%M:%S") \"Waking up\" >> /tmp/sleep.log" >> ~/.wakeup
		echo "sleep 7" >> ~/.wakeup
		echo "/usr/sbin/networksetup setairportpower en0 on" >> ~/.wakeup
		echo "echo $(date "+%Y-%m-%d %H:%M:%S") `/usr/sbin/networksetup getairportpower en0` >> /tmp/sleep.log" >> ~/.wakeup
	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo

	echo "Create plist file and copy to ~/Library/LaunchAgents ..."

	plistPath="/tmp/de.bernhard-baehr.sleepwatcher.plist"
	rm -rf ${plistPath} 
	touch ${plistPath}
	echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" >> ${plistPath}
	echo "<!DOCTYPE plist PUBLIC \"-//Apple Computer//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">" >> ${plistPath}
	echo "<plist version=\"1.0\">" >> ${plistPath}
	echo "<dict>" >> ${plistPath}
	echo "	<key>Label</key>" >> ${plistPath}
	echo "	<string>de.bernhard-baehr.sleepwatcher</string>" >> ${plistPath}
	echo "	<key>ProgramArguments</key>" >> ${plistPath}
	echo "	<array>" >> ${plistPath}
	echo "		<string>/usr/local/sbin/sleepwatcher</string>" >> ${plistPath}
	echo "		<string>-V</string>" >> ${plistPath}
	echo "		<string>-s ~/.sleep</string>" >> ${plistPath}
	echo "		<string>-w ~/.wakeup</string>" >> ${plistPath}
	echo "	</array>" >> ${plistPath}
	echo "	<key>RunAtLoad</key>" >> ${plistPath}
	echo "	<true/>" >> ${plistPath}
	echo "	<key>KeepAlive</key>" >> ${plistPath}
	echo "	<true/>" >> ${plistPath}
	echo "</dict>" >> ${plistPath}
	echo "</plist>" >> ${plistPath}
	
	mv ${plistPath} ~/Library/LaunchAgents

	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo

	echo "Starting PleaseSleep"
	launchctl load ~/Library/LaunchAgents/de.bernhard-baehr.sleepwatcher.plist
	echo "Done."
	echo "(Press ENTER key to continue.)"
	read
	echo
	echo
	echo "-------------------------------------------------------------------"
	echo
	echo "Path to wake script: ~/.wakeup"
	echo "Path to sleep script: ~/.sleep"
	echo "Path to logging file: /tmp/sleep.log"
	echo
	echo "Note that WiFi will only turn on 7 seconds AFTER your Mac has been waked"
	echo
	echo "-------------------------------------------------------------------"
	echo
	echo
	echo
	echo "IF NO ERRORS WERE FOUND, THEN INSTALLATION IS COMPLETE."
	echo
	echo "Your lovely Mac will sleep like a boss now!"
	echo
	echo
	echo

fi